// Zod validation schemas for the Shadow Cards API
  // (merged from lib/api-zod)

  import * as zod from "zod";

  // ── AuthUser TypeScript type ────────────────────────────────────────────────
  export interface AuthUser {
    id: string;
    email: string | null;
    firstName: string | null;
    lastName: string | null;
    profileImageUrl: string | null;
  }

  // ── Generated Zod schemas ───────────────────────────────────────────────────
  /**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Shadow Cards API — scrapes and serves shoob.gg anime card data
 * OpenAPI spec version: 0.1.0
 */

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Get the currently authenticated user
 */
export const GetCurrentAuthUserHeader = zod.object({
  Authorization: zod
    .string()
    .optional()
    .describe("Opaque session token — Bearer <sid>."),
});

export const GetCurrentAuthUserResponse = zod.object({
  user: zod.union([
    zod.object({
      id: zod.string(),
      email: zod.string().email().nullable(),
      firstName: zod.string().nullable(),
      lastName: zod.string().nullable(),
      profileImageUrl: zod.string().nullable(),
    }),
    zod.null(),
  ]),
});

/**
 * @summary Start the browser OIDC login flow
 */
export const BeginBrowserLoginQueryParams = zod.object({
  returnTo: zod.coerce.string().optional(),
});

/**
 * @summary Complete the browser OIDC login flow
 */
export const HandleBrowserLoginCallbackQueryParams = zod.object({
  code: zod.coerce.string().optional(),
  state: zod.coerce.string().optional(),
  iss: zod.coerce.string().url().optional(),
});

/**
 * @summary Clear the session and begin OIDC logout
 */
export const LogoutBrowserSessionHeader = zod.object({
  Authorization: zod
    .string()
    .optional()
    .describe("Opaque session token — Bearer <sid>."),
});

/**
 * @summary Exchange a mobile OIDC code for a session token
 */

export const ExchangeMobileAuthorizationCodeBody = zod.object({
  code: zod.string().min(1),
  code_verifier: zod.string().min(1),
  redirect_uri: zod.string().url().min(1),
  state: zod.string().min(1),
  nonce: zod.string().min(1).optional(),
});

export const ExchangeMobileAuthorizationCodeResponse = zod.object({
  token: zod.string(),
});

/**
 * @summary Delete a mobile session token
 */
export const LogoutMobileSessionHeader = zod.object({
  Authorization: zod
    .string()
    .optional()
    .describe("Opaque session token — Bearer <sid>."),
});

export const LogoutMobileSessionResponse = zod.object({
  success: zod.boolean(),
});

/**
 * @summary List cards from shoob.gg (scraped)
 */
export const listCardsQueryPageDefault = 1;
export const listCardsQueryLimitDefault = 15;

export const ListCardsQueryParams = zod.object({
  page: zod.coerce.number().default(listCardsQueryPageDefault),
  limit: zod.coerce.number().default(listCardsQueryLimitDefault),
  search: zod.coerce.string().optional(),
  tier: zod.coerce.string().optional(),
});

export const ListCardsResponse = zod.object({
  cards: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      series: zod.string(),
      tier: zod.string(),
      rarity: zod.string().optional(),
      imageUrl: zod.string(),
      thumbnailUrl: zod.string().optional(),
      totalIssues: zod.number().optional(),
    }),
  ),
  total: zod.number(),
  page: zod.number(),
  totalPages: zod.number(),
});

/**
 * @summary Total card counts and tier breakdown
 */
export const GetCardStatsResponse = zod.object({
  total: zod.number(),
  byTier: zod.record(zod.string(), zod.number()),
});

/**
 * @summary Featured/trending cards for the homepage
 */
export const GetFeaturedCardsResponseItem = zod.object({
  id: zod.string(),
  name: zod.string(),
  series: zod.string(),
  tier: zod.string(),
  rarity: zod.string().optional(),
  imageUrl: zod.string(),
  thumbnailUrl: zod.string().optional(),
  totalIssues: zod.number().optional(),
});
export const GetFeaturedCardsResponse = zod.array(GetFeaturedCardsResponseItem);

/**
 * @summary Get a single card by its shoob.gg ID
 */
export const GetCardParams = zod.object({
  id: zod.coerce.string(),
});

export const GetCardResponse = zod.object({
  id: zod.string(),
  name: zod.string(),
  series: zod.string(),
  tier: zod.string(),
  rarity: zod.string().optional(),
  imageUrl: zod.string(),
  thumbnailUrl: zod.string().optional(),
  totalIssues: zod.number().optional(),
});

/**
 * @summary Proxy and upscale a card image URL
 */
export const imageProxyQueryScaleDefault = 2;

export const ImageProxyQueryParams = zod.object({
  url: zod.coerce.string(),
  scale: zod.coerce.number().default(imageProxyQueryScaleDefault),
});

  